#version: '3' <-- specifies docker compose version
services:
  app:
    restart: always
    #build: . # docker compose looks for Dockerfile in the directory after the . and build accordingly
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 127.0.0.1:5000:5000
    networks:
      - mynetwork
    volumes:
      - .:/usr/src/app-data
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - 5432:5432
    networks:
      - mynetwork
    volumes:
      - database:/var/lib/postgresql/data/
    expose:
      - 5432

  #frontend:
   # build:
    #  context: .
     # dockerfile: Dockerfile.frontend
    #ports:
     # - 127.0.0.1:3000:3000
    #networks:
    #  - mynetwork
    #volumes:
    #  - ./fastfront2/src:/app/src
    #depends_on:
    #  - postgres
    #  - app

networks:
  mynetwork:

volumes:
  database:
