# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY ./fastfront2/package.json /app/package.json

COPY ./fastfront2/package-lock.json /app/package-lock.json

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY ./fastfront2 /app

# Expose port 80 (80 or 3000 does not matter?)
EXPOSE 80

# Command to start the development server
CMD ["npm", "start"]

