name: deploy to EC2
run-name: ${{ github.actor }} is trying to deploy to AWS EC2
on: [push] #any branch testing
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4 
      
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build the Docker image 
        run: docker build -f Dockerfile.frontend -t fast-api_v1 . 
          #docker build -f Dockerfile.backend . 
      - name: Push to Dockerhub
        run: | 
          docker tag fast-api_v1 cth06docker/fast-api_v1
          docker push cth06docker/fast-api_v1:latest
  
  ec2:
    needs: dockerhub 
    runs-on: self-hosted 
    steps: 
      - name: Allow Docker socket connection
        run: sudo chmod 666 /var/run/docker.sock
      - name: Pull image from docker hub 
        run: docker pull cth06docker/fast-api_v1:latest 
      - name: Delete old container if present
        run: | 
          CONTAINER_ID=$(docker ps -q -f "name=hello")
          echo $CONTAINER_ID
          if [CONTAINER_ID != ""]; then
            docker rm -f hello
            echo "container check done"
          fi 
      - name: Run Docker container 
        #run: docker compose up
        run: docker run -dp 127.0.0.1:80:3000 --name hello cth06docker/fast-api_v1:latest
 
