name: deploy to EC2
run-name: ${{ github.actor }} is trying to deploy to AWS EC2
on: [push] #any branch test
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4 
      
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build both Docker images 
        run: | 
          docker build -f Dockerfile.frontend -t fast-api-frontend . 
          docker build -f Dockerfile.backend -t fast-api-backend . 
      - name: Push both images to Dockerhub
        run: | 
          docker tag fast-api-frontend cth06docker/fast-api_v1:frontend
          docker tag fast-api-backend cth06docker/fast-api_v1:backend
          docker push cth06docker/fast-api_v1:frontend
          docker push cth06docker/fast-api_v1:backend
  
  ec2:
    needs: dockerhub 
    runs-on: self-hosted 
    steps: 
      - uses: actions/checkout@v4       

      - name: Allow Docker socket connection
        run: sudo chmod 666 /var/run/docker.sock
      - name: Clear space in EC2
        run: | 
          docker system prune -a
          y
      - name: Run docker compose 
        run: docker compose up --build
      - name: Pull image from docker hub 
        run: | 
          docker pull cth06docker/fast-api_v1:frontend
          docker pull cth06docker/fast-api_v1:backend 
      - name: Delete old container if present
        run: | 
          CONTAINER_ID_frontend=$(docker ps -q -f "name=frontend")
          CONTAINER_ID_backend=$(docker ps -q -f "name=backend")
          echo $CONTAINER_ID_frontend
          echo $CONTAINER_ID_backend
          CONTAINER_ID_TOTAL="$CONTAINER_ID_frontend $CONTAINER_ID_backend"
          if [ -n "$CONTAINER_ID_TOTAL" ]; then
            docker stop $CONTAINER_ID_TOTAL
            docker remove $CONTAINER_ID_TOTAL
            echo "containers removed done"
          fi 
      - name: Run Docker containers 
        #run: docker compose up
        run: |  
          docker run -dp 172.31.62.107:80:3000 --name frontend cth06docker/fast-api_v1:frontend
          docker run -dp 172.31.62.107:5000:5000 --name backend cth06docker/fast-api_v1:backend
        #cannot localhost or EC2 public network. Must be EC2 private network.
 
