name: deploy to EC2
run-name: ${{ github.actor }} is trying to deploy to AWS EC2
on: [push] #any branch test
jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4 
      
      - name: Login to Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build both Docker images 
        run: | 
          docker build -f Dockerfile.frontend -t fast-api-frontend . 
          docker build -f Dockerfile.backend -t fast-api-backend . 
      - name: Push both images to Dockerhub
        run: | 
          docker tag fast-api-frontend cth06docker/fast-api_v1:frontend
          docker tag fast-api-backend cth06docker/fast-api_v1:backend
          docker push cth06docker/fast-api_v1:frontend
          docker push cth06docker/fast-api_v1:backend
  
  ec2:
    needs: dockerhub 
    runs-on: self-hosted 
    steps: 
      - uses: actions/checkout@v4       

      - name: Allow Docker socket connection
        run: sudo chmod 666 /var/run/docker.sock
      - name: Clear space in EC2
        run: docker system prune -af
      - name: Remove any existing containers
        run: |
          CONTAINER_ID_TOTAL=$(docker ps -a -q)
          if [ -n "$CONTAINER_ID_TOTAL" ]; then
            docker stop $(docker ps -a -q)
            docker remove $(docker ps -a -q)
            echo "containers removed done"
          fi 
      - name: Run docker compose up
        run: docker compose up --build