name: GitHub Actions eslint
run-name: ${{ github.actor }} is trying out eslint check

#if branches are not defined, it refers to all branches?
on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: eslint
        run: |
          cd fastfront2
          npm install
          npm run eslint . --ext .js,.jsx,.ts,.tsx 
